from flask import Flask, request, jsonify, Response
import os
import json
from sesamutils import sesam_logger

app = Flask(__name__)
logger = sesam_logger("Steve the logger", app=app)

@app.route('/')
def index():
    output = {
        'service': 'Learn Sesam - up and running',
        'remote_addr': request.remote_addr
    }
    return jsonify(output)

###
# Do the magic.
###
@app.route('/company', methods=['GET','POST'])
def get_company_data():

    embedded_data = [
    {
      "_id": "4848090102",
      "archived": False,
      "createdAt": "2021-09-20T06:42:06.233Z",
      "id": "4848090102",
      "properties": {
        "type": None,
        "name": "ADITRO BPO AS",
        "description": "En av Nordens største og mest anerkjente leverandører av lønnssystem, HR-system og outsourcing av lønnstjenester til større selskaper.",
        "about_us": "813285762",
        "address": "POSTBOKS 23",
        "address2": None,
        "annualrevenue": "10000000",
        "city": "Gran",
        "closedate": None,
        "country": "Norway",
        "createdate": "2021-09-20T06:42:06.233Z",
        "days_to_close": None,
        "domain": "aditro.no",
        "engagements_last_meeting_booked": None,
        "engagements_last_meeting_booked_campaign": None,
        "engagements_last_meeting_booked_medium": None,
        "engagements_last_meeting_booked_source": None,
        "facebook_company_page": None,
        "facebookfans": None,
        "first_contact_createdate": None,
        "first_deal_created_date": None,
        "founded_year": "2014",
        "googleplus_page": None,
        "hs_analytics_first_timestamp": None,
        "hs_analytics_first_touch_converting_campaign": None,
        "hs_analytics_first_visit_timestamp": None,
        "hs_analytics_last_timestamp": None,
        "hs_analytics_last_touch_converting_campaign": None,
        "hs_analytics_last_visit_timestamp": None,
        "hs_analytics_num_page_views": None,
        "hs_analytics_num_visits": None,
        "hs_analytics_source": None,
        "hs_analytics_source_data_1": None,
        "hs_analytics_source_data_2": None,
        "hs_createdate": None,
        "hs_ideal_customer_profile": None,
        "hs_is_target_account": None,
        "hs_last_booked_meeting_date": None,
        "hs_last_logged_call_date": None,
        "hs_last_open_task_date": None,
        "hs_last_sales_activity_timestamp": None,
        "hs_lastmodifieddate": "2022-04-26T11:33:11.336Z",
        "hs_lead_status": None,
        "hs_num_blockers": "0",
        "hs_num_child_companies": "0",
        "hs_num_contacts_with_buying_roles": "0",
        "hs_num_decision_makers": "0",
        "hs_num_open_deals": "0",
        "hs_object_id": "4848090102",
        "hs_parent_company_id": None,
        "hs_total_deal_value": None,
        "hubspot_owner_assigneddate": None,
        "hubspot_owner_id": None,
        "hubspot_team_id": None,
        "industry": None,
        "is_public": "False",
        "lifecyclestage": None,
        "linkedin_company_page": "https://www.linkedin.com/company/aditro",
        "linkedinbio": "En av Nordens største og mest anerkjente leverandører av lønnssystem, HR-system og outsourcing av lønnstjenester til større selskaper.",
        "notes_last_contacted": None,
        "notes_last_updated": None,
        "notes_next_activity_date": None,
        "num_associated_contacts": "0",
        "num_associated_deals": None,
        "num_contacted_notes": None,
        "numberofemployees": None,
        "phone": None,
        "recent_deal_amount": None,
        "recent_deal_close_date": None,
        "state": "Oppland",
        "timezone": "Europe/Oslo",
        "total_money_raised": None,
        "total_revenue": None,
        "twitterbio": None,
        "twitterfollowers": None,
        "twitterhandle": "aditroonline",
        "web_technologies": "youtube;typekit_by_adobe;nginx;google_maps;wordpress;google_cloud;google_tag_manager;pardot;wistia;double_click",
        "website": "aditro.no",
        "zip": "2711"
      },
      "updatedAt": "2022-04-26T11:33:11.336Z"
    },{
      "_id": "4849414393",
      "archived": False,
      "createdAt": "2021-09-20T14:07:10.721Z",
      "id": "4849414393",
      "properties": {
        "type": None,
        "name": "Zovio Inc",
        "description": "Education has transformed. Has your classroom? At Zovio, we know there’s a smarter way to learn by using data, and we have over a decade of experience creating personalized educational opportunities. From finding and enrolling students to optimizing learning solutions, our approach is designed to deliver change that matters.",
        "about_us": "915713769",
        "address": "1811 East Northrop Boulevard",
        "address2": None,
        "annualrevenue": None,
        "city": "Chandler",
        "closedate": None,
        "country": "United States",
        "createdate": "2021-09-20T14:07:10.721Z",
        "days_to_close": None,
        "domain": "zovio.com",
        "engagements_last_meeting_booked": None,
        "engagements_last_meeting_booked_campaign": None,
        "engagements_last_meeting_booked_medium": None,
        "engagements_last_meeting_booked_source": None,
        "facebook_company_page": "https://www.facebook.com/ZovioSolutions",
        "facebookfans": None,
        "first_contact_createdate": None,
        "first_deal_created_date": None,
        "founded_year": "2004",
        "googleplus_page": None,
        "hs_analytics_first_timestamp": None,
        "hs_analytics_first_touch_converting_campaign": None,
        "hs_analytics_first_visit_timestamp": None,
        "hs_analytics_last_timestamp": None,
        "hs_analytics_last_touch_converting_campaign": None,
        "hs_analytics_last_visit_timestamp": None,
        "hs_analytics_num_page_views": None,
        "hs_analytics_num_visits": None,
        "hs_analytics_source": None,
        "hs_analytics_source_data_1": None,
        "hs_analytics_source_data_2": None,
        "hs_createdate": None,
        "hs_ideal_customer_profile": None,
        "hs_is_target_account": None,
        "hs_last_booked_meeting_date": None,
        "hs_last_logged_call_date": None,
        "hs_last_open_task_date": None,
        "hs_last_sales_activity_timestamp": None,
        "hs_lastmodifieddate": "2022-04-22T14:59:47.252Z",
        "hs_lead_status": None,
        "hs_num_blockers": "0",
        "hs_num_child_companies": "0",
        "hs_num_contacts_with_buying_roles": "0",
        "hs_num_decision_makers": "0",
        "hs_num_open_deals": "0",
        "hs_object_id": "4849414393",
        "hs_parent_company_id": None,
        "hs_total_deal_value": None,
        "hubspot_owner_assigneddate": None,
        "hubspot_owner_id": None,
        "hubspot_team_id": None,
        "industry": None,
        "is_public": "False",
        "lifecyclestage": None,
        "linkedin_company_page": None,
        "linkedinbio": None,
        "notes_last_contacted": None,
        "notes_last_updated": None,
        "notes_next_activity_date": None,
        "num_associated_contacts": "0",
        "num_associated_deals": None,
        "num_contacted_notes": None,
        "numberofemployees": None,
        "phone": None,
        "recent_deal_amount": None,
        "recent_deal_close_date": None,
        "state": "Arizona",
        "timezone": "MST/Arizona",
        "total_money_raised": None,
        "total_revenue": None,
        "twitterbio": None,
        "twitterfollowers": None,
        "twitterhandle": "zovio",
        "web_technologies": None,
        "website": "zovio.com",
        "zip": "85286"
      },
      "updatedAt": "2022-04-22T14:59:47.252Z"
    },{
      "_id": "4849463506",
      "archived": False,
      "createdAt": "2021-09-20T14:02:24.010Z",
      "id": "4849463506",
      "properties": {
        "type": None,
        "name": "THEMOON AS",
        "description": "TheMOON offers complete flexibility to create and develop shops which incorporate new design and new solutions on an everyday basis. The size and shape can change as the concept changes. This high tech community provides the solution that matches your exact needs. TheMOON and its unique tools take retailers closer to consumers.",
        "about_us": "991721355",
        "address": "4 Øvre Slottsgate",
        "address2": None,
        "annualrevenue": "1000000",
        "city": "Oslo",
        "closedate": None,
        "country": "Norway",
        "createdate": "2021-09-20T14:02:24.010Z",
        "days_to_close": None,
        "domain": "themoon.com",
        "engagements_last_meeting_booked": None,
        "engagements_last_meeting_booked_campaign": None,
        "engagements_last_meeting_booked_medium": None,
        "engagements_last_meeting_booked_source": None,
        "facebook_company_page": None,
        "facebookfans": None,
        "first_contact_createdate": None,
        "first_deal_created_date": None,
        "founded_year": "2014",
        "googleplus_page": None,
        "hs_analytics_first_timestamp": None,
        "hs_analytics_first_touch_converting_campaign": None,
        "hs_analytics_first_visit_timestamp": None,
        "hs_analytics_last_timestamp": None,
        "hs_analytics_last_touch_converting_campaign": None,
        "hs_analytics_last_visit_timestamp": None,
        "hs_analytics_num_page_views": None,
        "hs_analytics_num_visits": None,
        "hs_analytics_source": None,
        "hs_analytics_source_data_1": None,
        "hs_analytics_source_data_2": None,
        "hs_createdate": None,
        "hs_ideal_customer_profile": None,
        "hs_is_target_account": None,
        "hs_last_booked_meeting_date": None,
        "hs_last_logged_call_date": None,
        "hs_last_open_task_date": None,
        "hs_last_sales_activity_timestamp": None,
        "hs_lastmodifieddate": "2022-04-20T13:28:20.166Z",
        "hs_lead_status": None,
        "hs_num_blockers": "0",
        "hs_num_child_companies": "0",
        "hs_num_contacts_with_buying_roles": "0",
        "hs_num_decision_makers": "0",
        "hs_num_open_deals": "0",
        "hs_object_id": "4849463506",
        "hs_parent_company_id": None,
        "hs_total_deal_value": None,
        "hubspot_owner_assigneddate": None,
        "hubspot_owner_id": None,
        "hubspot_team_id": None,
        "industry": None,
        "is_public": "False",
        "lifecyclestage": None,
        "linkedin_company_page": "https://www.linkedin.com/company/themoon",
        "linkedinbio": "TheMOON offers complete flexibility to create and develop shops which incorporate new design and new solutions on an everyday basis. The size and shape can change as the concept changes. This high tech community provides the solution that matches your exact needs. TheMOON and its unique tools take retailers closer to consumers.",
        "notes_last_contacted": None,
        "notes_last_updated": None,
        "notes_next_activity_date": None,
        "num_associated_contacts": "0",
        "num_associated_deals": None,
        "num_contacted_notes": None,
        "numberofemployees": None,
        "phone": None,
        "recent_deal_amount": None,
        "recent_deal_close_date": None,
        "state": "Oslo",
        "timezone": "Europe/Oslo",
        "total_money_raised": None,
        "total_revenue": None,
        "twitterbio": None,
        "twitterfollowers": None,
        "twitterhandle": None,
        "web_technologies": "microsoft_exchange_online;microsoft_office_365;vimeo;wordpress;outlook;amazon__cloudfront;google_tag_manager;cloud_flare",
        "website": "themoon.com",
        "zip": "0157"
      },
      "updatedAt": "2022-04-20T13:28:20.166Z"
    },{
      "_id": "4849410239",
      "archived": False,
      "createdAt": "2021-09-20T14:03:36.844Z",
      "id": "4849410239",
      "properties": {
        "type": None,
        "name": "UFORMIA AS",
        "description": "Creating a new generation 3D modeling system, based on real volumes - changing what is made, who makes it and how it is produced.",
        "about_us": "994297139",
        "address": "POSTBOKS 60",
        "address2": None,
        "annualrevenue": "1000000",
        "city": "Lyngseidet",
        "closedate": None,
        "country": "Norway",
        "createdate": "2021-09-20T14:03:36.844Z",
        "days_to_close": None,
        "domain": "uformia.no",
        "engagements_last_meeting_booked": None,
        "engagements_last_meeting_booked_campaign": None,
        "engagements_last_meeting_booked_medium": None,
        "engagements_last_meeting_booked_source": None,
        "facebook_company_page": None,
        "facebookfans": None,
        "first_contact_createdate": None,
        "first_deal_created_date": None,
        "founded_year": "2009",
        "googleplus_page": None,
        "hs_analytics_first_timestamp": None,
        "hs_analytics_first_touch_converting_campaign": None,
        "hs_analytics_first_visit_timestamp": None,
        "hs_analytics_last_timestamp": None,
        "hs_analytics_last_touch_converting_campaign": None,
        "hs_analytics_last_visit_timestamp": None,
        "hs_analytics_num_page_views": None,
        "hs_analytics_num_visits": None,
        "hs_analytics_source": None,
        "hs_analytics_source_data_1": None,
        "hs_analytics_source_data_2": None,
        "hs_createdate": None,
        "hs_ideal_customer_profile": None,
        "hs_is_target_account": None,
        "hs_last_booked_meeting_date": None,
        "hs_last_logged_call_date": None,
        "hs_last_open_task_date": None,
        "hs_last_sales_activity_timestamp": None,
        "hs_lastmodifieddate": "2022-04-19T02:46:11.073Z",
        "hs_lead_status": None,
        "hs_num_blockers": "0",
        "hs_num_child_companies": "0",
        "hs_num_contacts_with_buying_roles": "0",
        "hs_num_decision_makers": "0",
        "hs_num_open_deals": "0",
        "hs_object_id": "4849410239",
        "hs_parent_company_id": None,
        "hs_total_deal_value": None,
        "hubspot_owner_assigneddate": None,
        "hubspot_owner_id": None,
        "hubspot_team_id": None,
        "industry": None,
        "is_public": None,
        "lifecyclestage": None,
        "linkedin_company_page": "https://www.linkedin.com/company/uformia",
        "linkedinbio": "Creating a new generation 3D modeling system, based on real volumes - changing what is made, who makes it and how it is produced.",
        "notes_last_contacted": None,
        "notes_last_updated": None,
        "notes_next_activity_date": None,
        "num_associated_contacts": "0",
        "num_associated_deals": None,
        "num_contacted_notes": None,
        "numberofemployees": None,
        "phone": None,
        "recent_deal_amount": None,
        "recent_deal_close_date": None,
        "state": "Troms",
        "timezone": "Europe/Oslo",
        "total_money_raised": None,
        "total_revenue": None,
        "twitterbio": None,
        "twitterfollowers": None,
        "twitterhandle": "Uformia",
        "web_technologies": "amazon_s3;mailchimp;wordpress;woo_commerce",
        "website": "uformia.no",
        "zip": "9069"
      },
      "updatedAt": "2022-04-19T02:46:11.073Z"
    },{
      "_id": "4849396673",
      "archived": False,
      "createdAt": "2021-09-20T13:39:14.318Z",
      "id": "4849396673",
      "properties": {
        "type": None,
        "name": "Zaptec AS",
        "description": "Vi skal forandre verden til det bedre gjennom å skape en mer bærekraftig og elektrisk fremtid.",
        "about_us": "985095779",
        "address": "Professor Olav Hanssens vei 7A",
        "address2": None,
        "annualrevenue": None,
        "city": "Stavanger",
        "closedate": None,
        "country": "Norway",
        "createdate": "2021-09-20T13:39:14.318Z",
        "days_to_close": None,
        "domain": "zaptec.com",
        "engagements_last_meeting_booked": None,
        "engagements_last_meeting_booked_campaign": None,
        "engagements_last_meeting_booked_medium": None,
        "engagements_last_meeting_booked_source": None,
        "facebook_company_page": None,
        "facebookfans": None,
        "first_contact_createdate": None,
        "first_deal_created_date": None,
        "founded_year": "2012",
        "googleplus_page": None,
        "hs_analytics_first_timestamp": None,
        "hs_analytics_first_touch_converting_campaign": None,
        "hs_analytics_first_visit_timestamp": None,
        "hs_analytics_last_timestamp": None,
        "hs_analytics_last_touch_converting_campaign": None,
        "hs_analytics_last_visit_timestamp": None,
        "hs_analytics_num_page_views": None,
        "hs_analytics_num_visits": None,
        "hs_analytics_source": None,
        "hs_analytics_source_data_1": None,
        "hs_analytics_source_data_2": None,
        "hs_createdate": None,
        "hs_ideal_customer_profile": None,
        "hs_is_target_account": None,
        "hs_last_booked_meeting_date": None,
        "hs_last_logged_call_date": None,
        "hs_last_open_task_date": None,
        "hs_last_sales_activity_timestamp": None,
        "hs_lastmodifieddate": "2022-04-15T09:14:46.026Z",
        "hs_lead_status": None,
        "hs_num_blockers": "0",
        "hs_num_child_companies": "0",
        "hs_num_contacts_with_buying_roles": "0",
        "hs_num_decision_makers": "0",
        "hs_num_open_deals": "0",
        "hs_object_id": "4849396673",
        "hs_parent_company_id": None,
        "hs_total_deal_value": None,
        "hubspot_owner_assigneddate": None,
        "hubspot_owner_id": None,
        "hubspot_team_id": None,
        "industry": None,
        "is_public": "False",
        "lifecyclestage": None,
        "linkedin_company_page": "https://www.linkedin.com/company/gozaptec/",
        "linkedinbio": "Zaptec is a world leader in cloud-connected charging systems for multiple​ electric vehicles.",
        "notes_last_contacted": None,
        "notes_last_updated": None,
        "notes_next_activity_date": None,
        "num_associated_contacts": "0",
        "num_associated_deals": None,
        "num_contacted_notes": None,
        "numberofemployees": None,
        "phone": None,
        "recent_deal_amount": None,
        "recent_deal_close_date": None,
        "state": "Stavanger",
        "timezone": "Europe/Oslo",
        "total_money_raised": None,
        "total_revenue": None,
        "twitterbio": None,
        "twitterfollowers": None,
        "twitterhandle": None,
        "web_technologies": None,
        "website": "zaptec.com",
        "zip": "4021"
      },
      "updatedAt": "2022-04-15T09:14:46.026Z"
    },{
      "_id": "4849357255",
      "archived": False,
      "createdAt": "2021-09-20T13:36:13.744Z",
      "id": "4849357255",
      "properties": {
        "type": None,
        "name": "DESKTOP.COM AS",
        "description": "Desktop.com offers you the best digital workplace software for organizing and managing teams. Chat, video call, and collaborate across apps from one place today!",
        "about_us": "994956701",
        "address": "NEW YORK",
        "address2": None,
        "annualrevenue": "1000000",
        "city": "New York",
        "closedate": None,
        "country": "United States",
        "createdate": "2021-09-20T13:36:13.744Z",
        "days_to_close": None,
        "domain": "desktop.com",
        "engagements_last_meeting_booked": None,
        "engagements_last_meeting_booked_campaign": None,
        "engagements_last_meeting_booked_medium": None,
        "engagements_last_meeting_booked_source": None,
        "facebook_company_page": "https://www.facebook.com/idealab",
        "facebookfans": None,
        "first_contact_createdate": None,
        "first_deal_created_date": None,
        "founded_year": "2019",
        "googleplus_page": None,
        "hs_analytics_first_timestamp": None,
        "hs_analytics_first_touch_converting_campaign": None,
        "hs_analytics_first_visit_timestamp": None,
        "hs_analytics_last_timestamp": None,
        "hs_analytics_last_touch_converting_campaign": None,
        "hs_analytics_last_visit_timestamp": None,
        "hs_analytics_num_page_views": None,
        "hs_analytics_num_visits": None,
        "hs_analytics_source": None,
        "hs_analytics_source_data_1": None,
        "hs_analytics_source_data_2": None,
        "hs_createdate": None,
        "hs_ideal_customer_profile": None,
        "hs_is_target_account": None,
        "hs_last_booked_meeting_date": None,
        "hs_last_logged_call_date": None,
        "hs_last_open_task_date": None,
        "hs_last_sales_activity_timestamp": None,
        "hs_lastmodifieddate": "2022-04-01T22:24:15.304Z",
        "hs_lead_status": None,
        "hs_num_blockers": "0",
        "hs_num_child_companies": "0",
        "hs_num_contacts_with_buying_roles": "0",
        "hs_num_decision_makers": "0",
        "hs_num_open_deals": "0",
        "hs_object_id": "4849357255",
        "hs_parent_company_id": None,
        "hs_total_deal_value": None,
        "hubspot_owner_assigneddate": None,
        "hubspot_owner_id": None,
        "hubspot_team_id": None,
        "industry": "COMPUTER_SOFTWARE",
        "is_public": "False",
        "lifecyclestage": None,
        "linkedin_company_page": "https://www.linkedin.com/company/desktop-com",
        "linkedinbio": "Desktop.com offers you the best digital workplace software for organizing and managing teams. Chat, video call, and collaborate across apps from one place today!",
        "notes_last_contacted": None,
        "notes_last_updated": None,
        "notes_next_activity_date": None,
        "num_associated_contacts": "0",
        "num_associated_deals": None,
        "num_contacted_notes": None,
        "numberofemployees": None,
        "phone": None,
        "recent_deal_amount": None,
        "recent_deal_close_date": None,
        "state": "NY",
        "timezone": "America/New_York",
        "total_money_raised": None,
        "total_revenue": None,
        "twitterbio": None,
        "twitterfollowers": None,
        "twitterhandle": "Desktop_dot_com",
        "web_technologies": "amazon_s3;google_tag_manager;facebook_connect;google_analytics;intercom;google_apps;hubspot;facebook_advertiser;amazon__cloudfront;cloud_flare",
        "website": "desktop.com",
        "zip": "94133"
      },
      "updatedAt": "2022-04-01T22:24:15.304Z"
    },{
      "archived": False,
      "createdAt": "2021-09-20T13:36:57.861Z",
      "id": "4849358801",
      "properties": {
        "about_us": "990551561",
        "address": "72 Hardangervegen",
        "address2": None,
        "annualrevenue": "10000000",
        "city": "Nesttun",
        "closedate": None,
        "country": "Norway",
        "createdate": "2021-09-20T13:36:57.861Z",
        "days_to_close": None,
        "description": "SIKKER DRIFT, SERVICE OG SUPPORT TJENESTER, First IT HAR SPISSKOMPETANSEN Your Content Goes Here On-site og Remote Your Content Goes Here Your Content Goes Here Din partner innenfor Drift, support og sikkerhet Av...",
        "domain": "firstit.no",
        "engagements_last_meeting_booked": None,
        "engagements_last_meeting_booked_campaign": None,
        "engagements_last_meeting_booked_medium": None,
        "engagements_last_meeting_booked_source": None,
        "facebook_company_page": "https://facebook.com/firstitas",
        "facebookfans": None,
        "first_contact_createdate": None,
        "first_deal_created_date": None,
        "founded_year": "2006",
        "googleplus_page": None,
        "hs_analytics_first_timestamp": None,
        "hs_analytics_first_touch_converting_campaign": None,
        "hs_analytics_first_visit_timestamp": None,
        "hs_analytics_last_timestamp": None,
        "hs_analytics_last_touch_converting_campaign": None,
        "hs_analytics_last_visit_timestamp": None,
        "hs_analytics_num_page_views": None,
        "hs_analytics_num_visits": None,
        "hs_analytics_source": None,
        "hs_analytics_source_data_1": None,
        "hs_analytics_source_data_2": None,
        "hs_createdate": None,
        "hs_ideal_customer_profile": None,
        "hs_is_target_account": None,
        "hs_last_booked_meeting_date": None,
        "hs_last_logged_call_date": None,
        "hs_last_open_task_date": None,
        "hs_last_sales_activity_timestamp": None,
        "hs_lastmodifieddate": "2022-05-05T09:08:11.368Z",
        "hs_lead_status": None,
        "hs_num_blockers": "0",
        "hs_num_child_companies": "0",
        "hs_num_contacts_with_buying_roles": "0",
        "hs_num_decision_makers": "0",
        "hs_num_open_deals": "0",
        "hs_object_id": "4849358801",
        "hs_parent_company_id": None,
        "hs_total_deal_value": None,
        "hubspot_owner_assigneddate": None,
        "hubspot_owner_id": None,
        "hubspot_team_id": None,
        "industry": "COMPUTER_SOFTWARE",
        "is_public": "false",
        "lifecyclestage": None,
        "linkedin_company_page": "https://www.linkedin.com/company/first-it-as",
        "linkedinbio": "SIKKER DRIFT, SERVICE OG SUPPORT TJENESTER, First IT HAR SPISSKOMPETANSEN Your Content Goes Here On-site og Remote Your Content Goes Here Your Content Goes Here Din partner innenfor Drift, support og sikkerhet Av...",
        "name": "FIRST IT AS",
        "notes_last_contacted": None,
        "notes_last_updated": None,
        "notes_next_activity_date": None,
        "num_associated_contacts": "0",
        "num_associated_deals": None,
        "num_contacted_notes": None,
        "numberofemployees": "10",
        "phone": "+47 55 62 19 00",
        "recent_deal_amount": None,
        "recent_deal_close_date": None,
        "state": "Hordaland",
        "timezone": "Europe/Oslo",
        "total_money_raised": None,
        "total_revenue": None,
        "twitterbio": None,
        "twitterfollowers": None,
        "twitterhandle": "_amyjojohnson",
        "type": None,
        "web_technologies": "microsoft_exchange_online;youtube;freshdesk;nginx;wordpress;google_tag_manager;woo_commerce;microsoft_office_365;google_maps;go_squared;google_analytics;twitter_button;outlook",
        "website": "firstit.no",
        "zip": "5224"
      },
      "updatedAt": "2022-05-05T09:08:11.368Z"
    },{
      "archived": False,
      "createdAt": "2021-09-20T13:37:53.824Z",
      "id": "4849384388",
      "properties": {
        "about_us": "981967070",
        "address": "33B Schweigaards gate",
        "address2": None,
        "annualrevenue": "50000000",
        "city": "Oslo",
        "closedate": None,
        "country": "Norway",
        "createdate": "2021-09-20T13:37:53.824Z",
        "days_to_close": None,
        "description": "En komplett plattformtjeneste for multicloud IT-miljøer Intility er en ende-til-ende plattformtjeneste som benyttes av mer enn 600 selskaper på tvers av",
        "domain": "intility.no",
        "engagements_last_meeting_booked": None,
        "engagements_last_meeting_booked_campaign": None,
        "engagements_last_meeting_booked_medium": None,
        "engagements_last_meeting_booked_source": None,
        "facebook_company_page": "https://facebook.com/intility",
        "facebookfans": None,
        "first_contact_createdate": None,
        "first_deal_created_date": None,
        "founded_year": "2000",
        "googleplus_page": None,
        "hs_analytics_first_timestamp": None,
        "hs_analytics_first_touch_converting_campaign": None,
        "hs_analytics_first_visit_timestamp": None,
        "hs_analytics_last_timestamp": None,
        "hs_analytics_last_touch_converting_campaign": None,
        "hs_analytics_last_visit_timestamp": None,
        "hs_analytics_num_page_views": None,
        "hs_analytics_num_visits": None,
        "hs_analytics_source": None,
        "hs_analytics_source_data_1": None,
        "hs_analytics_source_data_2": None,
        "hs_createdate": None,
        "hs_ideal_customer_profile": None,
        "hs_is_target_account": None,
        "hs_last_booked_meeting_date": None,
        "hs_last_logged_call_date": None,
        "hs_last_open_task_date": None,
        "hs_last_sales_activity_timestamp": None,
        "hs_lastmodifieddate": "2022-05-05T08:14:10.330Z",
        "hs_lead_status": None,
        "hs_num_blockers": "0",
        "hs_num_child_companies": "0",
        "hs_num_contacts_with_buying_roles": "0",
        "hs_num_decision_makers": "0",
        "hs_num_open_deals": "0",
        "hs_object_id": "4849384388",
        "hs_parent_company_id": None,
        "hs_total_deal_value": None,
        "hubspot_owner_assigneddate": None,
        "hubspot_owner_id": None,
        "hubspot_team_id": None,
        "industry": "COMPUTER_SOFTWARE",
        "is_public": "false",
        "lifecyclestage": None,
        "linkedin_company_page": "https://www.linkedin.com/company/intility-as",
        "linkedinbio": "En komplett plattformtjeneste for multicloud IT-miljøer Intility er en ende-til-ende plattformtjeneste som benyttes av mer enn 600 selskaper på tvers av",
        "name": "INTILITY AS",
        "notes_last_contacted": None,
        "notes_last_updated": None,
        "notes_next_activity_date": None,
        "num_associated_contacts": "0",
        "num_associated_deals": None,
        "num_contacted_notes": None,
        "numberofemployees": "500",
        "phone": "+47 24 10 33 00",
        "recent_deal_amount": None,
        "recent_deal_close_date": None,
        "state": "Oslo",
        "timezone": "Europe/Oslo",
        "total_money_raised": None,
        "total_revenue": None,
        "twitterbio": None,
        "twitterfollowers": None,
        "twitterhandle": "intility",
        "type": None,
        "web_technologies": "microsoft_exchange_online;wordpress;salesforce;apache;app_nexus;red_hat;google_tag_manager;sendgrid;microsoft_office_365;media_math;vimeo;outlook",
        "website": "intility.no",
        "zip": "0191"
      },
      "updatedAt": "2022-05-05T08:14:10.330Z"
    },{
      "archived": False,
      "createdAt": "2021-09-20T13:37:16.917Z",
      "id": "4849358835",
      "properties": {
        "about_us": "914527260",
        "address": "SKÅDALSVEIEN 4C",
        "address2": None,
        "annualrevenue": "1000000",
        "city": "Oslo",
        "closedate": None,
        "country": "Norway",
        "createdate": "2021-09-20T13:37:16.917Z",
        "days_to_close": None,
        "description": "GoDigi AS delivers digital innovation. \\r\\nWe identify and whip out digital potential.\\r\\n\\r\\nDigital Product Development and Consultancy.\\r\\nWe facilitiate and manage the production of digital products for desktop, tablet and mobile. \\r\\nThe time to market is kept short by utilizing highly qualified and experienced freelance specialists. \\r\\n\\r\\nWe aspire to deliver quality and have fun.",
        "domain": "godigi.no",
        "engagements_last_meeting_booked": None,
        "engagements_last_meeting_booked_campaign": None,
        "engagements_last_meeting_booked_medium": None,
        "engagements_last_meeting_booked_source": None,
        "facebook_company_page": None,
        "facebookfans": None,
        "first_contact_createdate": None,
        "first_deal_created_date": None,
        "founded_year": "2014",
        "googleplus_page": None,
        "hs_analytics_first_timestamp": None,
        "hs_analytics_first_touch_converting_campaign": None,
        "hs_analytics_first_visit_timestamp": None,
        "hs_analytics_last_timestamp": None,
        "hs_analytics_last_touch_converting_campaign": None,
        "hs_analytics_last_visit_timestamp": None,
        "hs_analytics_num_page_views": None,
        "hs_analytics_num_visits": None,
        "hs_analytics_source": None,
        "hs_analytics_source_data_1": None,
        "hs_analytics_source_data_2": None,
        "hs_createdate": None,
        "hs_ideal_customer_profile": None,
        "hs_is_target_account": None,
        "hs_last_booked_meeting_date": None,
        "hs_last_logged_call_date": None,
        "hs_last_open_task_date": None,
        "hs_last_sales_activity_timestamp": None,
        "hs_lastmodifieddate": "2022-05-04T21:30:26.009Z",
        "hs_lead_status": None,
        "hs_num_blockers": "0",
        "hs_num_child_companies": "0",
        "hs_num_contacts_with_buying_roles": "0",
        "hs_num_decision_makers": "0",
        "hs_num_open_deals": "0",
        "hs_object_id": "4849358835",
        "hs_parent_company_id": None,
        "hs_total_deal_value": None,
        "hubspot_owner_assigneddate": None,
        "hubspot_owner_id": None,
        "hubspot_team_id": None,
        "industry": "",
        "is_public": "false",
        "lifecyclestage": None,
        "linkedin_company_page": "https://www.linkedin.com/company/godigi-as",
        "linkedinbio": "GoDigi AS delivers digital innovation. \\r\\nWe identify and whip out digital potential.\\r\\n\\r\\nDigital Product Development and Consultancy.\\r\\nWe facilitiate and manage the production of digital products for desktop, tablet and mobile. \\r\\nThe time to market is kept short by utilizing highly qualified and experienced freelance specialists. \\r\\n\\r\\nWe aspire to deliver quality and have fun.",
        "name": "GODIGI AS",
        "notes_last_contacted": None,
        "notes_last_updated": None,
        "notes_next_activity_date": None,
        "num_associated_contacts": "0",
        "num_associated_deals": None,
        "num_contacted_notes": None,
        "numberofemployees": "10",
        "phone": None,
        "recent_deal_amount": None,
        "recent_deal_close_date": None,
        "state": "Oslo",
        "timezone": "Europe/Oslo",
        "total_money_raised": None,
        "total_revenue": None,
        "twitterbio": None,
        "twitterfollowers": None,
        "twitterhandle": None,
        "type": None,
        "web_technologies": "nginx;wordpress",
        "website": "godigi.no",
        "zip": "0781"
      },
      "updatedAt": "2022-05-04T21:30:26.009Z"
    },{
      "archived": False,
      "createdAt": "2021-09-20T14:01:56.752Z",
      "id": "4849463033",
      "properties": {
        "about_us": "985452954",
        "address": None,
        "address2": None,
        "annualrevenue": "1000000",
        "city": None,
        "closedate": None,
        "country": "Norway",
        "createdate": "2021-09-20T14:01:56.752Z",
        "days_to_close": None,
        "description": "Softarch Technologies As delivers mobile apps, web and digital consulting to companies across the globe with focus on scandanevian countries such as Norway, sweden and Denmark. Softarch specialises in web development, mobility, e-commerce, digital strategy, data analytics and outsourcing. We have clients across four continents. We are located in Norway.",
        "domain": "softarch.no",
        "engagements_last_meeting_booked": None,
        "engagements_last_meeting_booked_campaign": None,
        "engagements_last_meeting_booked_medium": None,
        "engagements_last_meeting_booked_source": None,
        "facebook_company_page": None,
        "facebookfans": None,
        "first_contact_createdate": None,
        "first_deal_created_date": None,
        "founded_year": "2003",
        "googleplus_page": None,
        "hs_analytics_first_timestamp": None,
        "hs_analytics_first_touch_converting_campaign": None,
        "hs_analytics_first_visit_timestamp": None,
        "hs_analytics_last_timestamp": None,
        "hs_analytics_last_touch_converting_campaign": None,
        "hs_analytics_last_visit_timestamp": None,
        "hs_analytics_num_page_views": None,
        "hs_analytics_num_visits": None,
        "hs_analytics_source": None,
        "hs_analytics_source_data_1": None,
        "hs_analytics_source_data_2": None,
        "hs_createdate": None,
        "hs_ideal_customer_profile": None,
        "hs_is_target_account": None,
        "hs_last_booked_meeting_date": None,
        "hs_last_logged_call_date": None,
        "hs_last_open_task_date": None,
        "hs_last_sales_activity_timestamp": None,
        "hs_lastmodifieddate": "2022-05-04T20:40:57.447Z",
        "hs_lead_status": None,
        "hs_num_blockers": "0",
        "hs_num_child_companies": "0",
        "hs_num_contacts_with_buying_roles": "0",
        "hs_num_decision_makers": "0",
        "hs_num_open_deals": "0",
        "hs_object_id": "4849463033",
        "hs_parent_company_id": None,
        "hs_total_deal_value": None,
        "hubspot_owner_assigneddate": None,
        "hubspot_owner_id": None,
        "hubspot_team_id": None,
        "industry": "INFORMATION_TECHNOLOGY_AND_SERVICES",
        "is_public": "false",
        "lifecyclestage": None,
        "linkedin_company_page": "https://www.linkedin.com/company/softarch-technologies-as",
        "linkedinbio": "Softarch Technologies As delivers mobile apps, web and digital consulting to companies across the globe with focus on scandanevian countries such as Norway, sweden and Denmark. Softarch specialises in web development, mobility, e-commerce, digital strategy, data analytics and outsourcing. We have clients across four continents. We are located in Norway.",
        "name": "SOFTARCH TECHNOLOGIES AS",
        "notes_last_contacted": None,
        "notes_last_updated": None,
        "notes_next_activity_date": None,
        "num_associated_contacts": "0",
        "num_associated_deals": None,
        "num_contacted_notes": None,
        "numberofemployees": "10",
        "phone": None,
        "recent_deal_amount": None,
        "recent_deal_close_date": None,
        "state": None,
        "timezone": None,
        "total_money_raised": None,
        "total_revenue": None,
        "twitterbio": None,
        "twitterfollowers": None,
        "twitterhandle": "",
        "type": None,
        "web_technologies": "microsoft_exchange_online;microsoft_office_365;nginx;hotjar;wordpress;go_squared;google_analytics;outlook",
        "website": "softarch.no",
        "zip": null
      },
      "updatedAt": "2022-05-04T20:40:57.447Z"
    }]
    return Response(json.dumps(embedded_data, separators=(',', ': ')), mimetype='application/json')

@app.route('/enhetsregisteret', methods=['GET','POST'])
def get_enhetsregisteret_data():
    embedded_data = [
    {
      "avvikling": "J",
      "forradrkommnavn": "BODØ",
      "forradrkommnr": "1804",
      "forradrland": "Norge",
      "forradrpostnr": "8006",
      "forradrpoststed": "BODØ",
      "forretningsadr": "H0507 c/o Reidar Andersen Dronningens gate 50B",
      "konkurs": "N",
      "navn": "SOFTARCH TECHNOLOGIES AS",
      "nkode1": "62.010",
      "organisasjonsform": "AS",
      "orgnr": "985452954",
      "postadresse": "Østensjøveien 81B",
      "ppostland": "Norge",
      "ppostnr": "0667",
      "ppoststed": "OSLO",
      "regdato": "02.04.2003",
      "regiaa": "N",
      "regifr": "J",
      "regifriv": "N",
      "regimva": "J",
      "regnskap": "2020",
      "sektorkode": "2100",
      "stiftelsesdato": "01.01.2003",
      "tlf": "75 55 83 55",
      "tlf_mobil": "472 78 128",
      "tvangsavvikling": "N",
      "url": "www.softarch.no"
    },{
      "ansatte_antall": "5",
      "ansatte_dato": "12.05.2021",
      "avvikling": "N",
      "forradrkommnavn": "BERGEN",
      "forradrkommnr": "4601",
      "forradrland": "Norge",
      "forradrpostnr": "5224",
      "forradrpoststed": "NESTTUN",
      "forretningsadr": "Hardangervegen 72",
      "konkurs": "N",
      "navn": "FIRST IT AS",
      "nkode1": "62.020",
      "organisasjonsform": "AS",
      "orgnr": "990551561",
      "regdato": "30.11.2006",
      "regiaa": "J",
      "regifr": "J",
      "regifriv": "N",
      "regimva": "J",
      "regnskap": "2020",
      "sektorkode": "2100",
      "stiftelsesdato": "27.10.2006",
      "tlf": "55 62 19 00",
      "tvangsavvikling": "N",
      "url": "www.firstit.no"
    },{
      "ansatte_antall": "490",
      "ansatte_dato": "19.04.2022",
      "avvikling": "N",
      "forradrkommnavn": "OSLO",
      "forradrkommnr": "0301",
      "forradrland": "Norge",
      "forradrpostnr": "0191",
      "forradrpoststed": "OSLO",
      "forretningsadr": "Schweigaards gate 39",
      "konkurs": "N",
      "navn": "INTILITY AS",
      "nkode1": "62.030",
      "organisasjonsform": "AS",
      "orgnr": "981967070",
      "regdato": "08.05.2000",
      "regiaa": "J",
      "regifr": "J",
      "regifriv": "N",
      "regimva": "J",
      "regnskap": "2020",
      "sektorkode": "2100",
      "stiftelsesdato": "27.04.2000",
      "tlf": "24 10 33 00",
      "tvangsavvikling": "N",
      "url": "intility.no"
    },{
      "ansatte_antall": "31",
      "ansatte_dato": "14.02.2022",
      "avvikling": "N",
      "forradrkommnavn": "OSLO",
      "forradrkommnr": "0301",
      "forradrland": "Norge",
      "forradrpostnr": "0191",
      "forradrpoststed": "OSLO",
      "forretningsadr": "Trelastgata 3",
      "konkurs": "N",
      "navn": "SD WORX BPO NORWAY AS",
      "nkode1": "62.020",
      "organisasjonsform": "AS",
      "orgnr": "813285762",
      "regdato": "25.02.2014",
      "regiaa": "J",
      "regifr": "J",
      "regifriv": "N",
      "regimva": "J",
      "regnskap": "2020",
      "sektorkode": "2100",
      "stiftelsesdato": "12.02.2014",
      "tlf": "21 95 96 00",
      "tvangsavvikling": "N",
      "url": "www.aditro.no"
    },{
      "ansatte_antall": "56",
      "ansatte_dato": "16.04.2022",
      "avvikling": "N",
      "forradrkommnavn": "OSLO",
      "forradrkommnr": "0301",
      "forradrland": "Norge",
      "forradrpostnr": "0484",
      "forradrpoststed": "OSLO",
      "forretningsadr": "Gjerdrums vei 10A",
      "konkurs": "N",
      "navn": "ZIVID AS",
      "nkode1": "62.010",
      "organisasjonsform": "AS",
      "orgnr": "915713769",
      "regdato": "28.07.2015",
      "regiaa": "J",
      "regifr": "J",
      "regifriv": "N",
      "regimva": "J",
      "regnskap": "2020",
      "sektorkode": "2100",
      "stiftelsesdato": "10.07.2015",
      "tlf": "21 02 24 71",
      "tvangsavvikling": "N",
      "url": "www.zivid.com"
    },{
      "avvikling": "N",
      "forradrkommnavn": "OSLO",
      "forradrkommnr": "0301",
      "forradrland": "Norge",
      "forradrpostnr": "0158",
      "forradrpoststed": "OSLO",
      "forretningsadr": "c/o Advokatfirmaet Sverdrup DA Akersgata 1",
      "konkurs": "J",
      "navn": "THEMOON AS",
      "nkode1": "63.120",
      "organisasjonsform": "AS",
      "orgnr": "991721355",
      "postadresse": "c/o Advokatfirmaet Sverdrup DA Postboks 1865 Vika",
      "ppostland": "Norge",
      "ppostnr": "0124",
      "ppoststed": "OSLO",
      "regdato": "18.09.2007",
      "regiaa": "N",
      "regifr": "J",
      "regifriv": "N",
      "regimva": "N",
      "regnskap": "2018",
      "sektorkode": "2100",
      "stiftelsesdato": "12.08.2007",
      "tvangsavvikling": "N",
      "url": "www.themoon.com"
    },{
      "avvikling": "N",
      "forradrkommnavn": "LYNGEN",
      "forradrkommnr": "5424",
      "forradrland": "Norge",
      "forradrpostnr": "9060",
      "forradrpoststed": "LYNGSEIDET",
      "forretningsadr": "Løvlandveien 16",
      "konkurs": "N",
      "navn": "UFORMIA AS",
      "nkode1": "62.020",
      "organisasjonsform": "AS",
      "orgnr": "994297139",
      "postadresse": "16869 SW 65th Ave, #131",
      "ppostland": "USA",
      "ppoststed": "Lake Oswego, OR 97209",
      "regdato": "15.07.2009",
      "regiaa": "N",
      "regifr": "J",
      "regifriv": "N",
      "regimva": "N",
      "regnskap": "2020",
      "sektorkode": "2100",
      "stiftelsesdato": "01.06.2009",
      "tlf_mobil": "+14252461094",
      "tvangsavvikling": "N",
      "url": "www.uformia.no"
    },{
      "ansatte_antall": "2",
      "ansatte_dato": "14.08.2019",
      "avvikling": "N",
      "forradrkommnavn": "ØYGARDEN",
      "forradrkommnr": "4626",
      "forradrland": "Norge",
      "forradrpostnr": "5363",
      "forradrpoststed": "ÅGOTNES",
      "forretningsadr": "Skjergardsvegen 1374",
      "konkurs": "N",
      "navn": "NORDIC SOLUTIONS AS",
      "nkode1": "62.020",
      "organisasjonsform": "AS",
      "orgnr": "985095779",
      "regdato": "27.11.2002",
      "regiaa": "J",
      "regifr": "J",
      "regifriv": "N",
      "regimva": "J",
      "regnskap": "2020",
      "sektorkode": "2100",
      "stiftelsesdato": "15.11.2002",
      "tlf": "56 33 61 71",
      "tvangsavvikling": "N",
      "url": "www.ns.no"
    },{
      "avvikling": "N",
      "forradrkommnavn": "OSLO",
      "forradrkommnr": "0301",
      "forradrland": "Norge",
      "forradrpostnr": "0252",
      "forradrpoststed": "OSLO",
      "forretningsadr": "c/o DNS Global AS 2. etasje Filipstad brygge 1",
      "konkurs": "N",
      "navn": "DESKTOP.COM AS",
      "nkode1": "62.010",
      "organisasjonsform": "AS",
      "orgnr": "994956701",
      "postadresse": "c/o Økonova 360 AS Krags gate 144",
      "ppostland": "Norge",
      "ppostnr": "4950",
      "ppoststed": "RISØR",
      "regdato": "06.01.2010",
      "regiaa": "N",
      "regifr": "J",
      "regifriv": "N",
      "regimva": "J",
      "regnskap": "2020",
      "sektorkode": "2100",
      "stiftelsesdato": "27.11.2009",
      "tlf_mobil": "414 11 111",
      "tvangsavvikling": "N",
      "url": "desktop.com"
    },{
      "avvikling": "N",
      "forradrkommnavn": "OSLO",
      "forradrkommnr": "0301",
      "forradrland": "Norge",
      "forradrpostnr": "0781",
      "forradrpoststed": "OSLO",
      "forretningsadr": "Skådalsveien 4C",
      "konkurs": "N",
      "navn": "GODIGI AS",
      "nkode1": "62.020",
      "organisasjonsform": "AS",
      "orgnr": "914527260",
      "regdato": "01.12.2014",
      "regiaa": "N",
      "regifr": "J",
      "regifriv": "N",
      "regimva": "N",
      "regnskap": "2020",
      "sektorkode": "2100",
      "stiftelsesdato": "04.11.2014",
      "tlf_mobil": "957 59 922",
      "tvangsavvikling": "N",
      "url": "www.godigi.no"
    }]

    return Response(json.dumps(embedded_data, separators=(',', ': ')), mimetype='application/json')

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000, debug=True, threaded=True)